import type { ThemeDefinition, ThemeShellPalette, ThemeSyntaxPalette } from '../types'
import { deriveAccentVariants } from '../utils'

function shell(
  accent: string,
  surfaces: Pick<
    ThemeShellPalette,
    | 'bgBase'
    | 'bgSurface'
    | 'bgElevated'
    | 'bgPanel'
    | 'bgHover'
    | 'bgActive'
    | 'bgInput'
    | 'textPrimary'
    | 'textSecondary'
    | 'textMuted'
    | 'textDisabled'
    | 'borderSubtle'
    | 'borderDefault'
    | 'borderStrong'
  >,
  extras?: Partial<Pick<ThemeShellPalette, 'danger' | 'warning' | 'success'>>,
): ThemeShellPalette {
  return {
    accent,
    ...deriveAccentVariants(accent),
    danger: extras?.danger ?? '#ff3b5c',
    warning: extras?.warning ?? '#ffb347',
    success: extras?.success ?? '#7fdbca',
    ...surfaces,
  }
}

function defineTheme(
  id: string,
  label: string,
  description: string,
  kind: ThemeDefinition['kind'],
  monacoBase: ThemeDefinition['monacoBase'],
  shellPalette: ThemeShellPalette,
  syntax: ThemeSyntaxPalette,
): ThemeDefinition {
  return {
    id,
    label,
    description,
    kind,
    monacoBase,
    shell: shellPalette,
    syntax,
    source: 'builtin',
  }
}

export const DEADEYE_DARK_THEME: ThemeDefinition = defineTheme(
  'deadeye-dark',
  'Deadeye Dark',
  'Signature Deadeye branding with charcoal surfaces and red crosshair accent.',
  'dark',
  'vs-dark',
  shell('#ff3b5c', {
    bgBase: '#080808',
    bgSurface: '#0a0a0a',
    bgElevated: '#101010',
    bgPanel: '#121212',
    bgHover: '#161616',
    bgActive: '#1a1a1a',
    bgInput: '#0e0e0e',
    textPrimary: '#f0f0f0',
    textSecondary: '#c8c8c8',
    textMuted: '#8a9098',
    textDisabled: '#5a5a5a',
    borderSubtle: '#1a1a1a',
    borderDefault: '#1e1e1e',
    borderStrong: '#2a2a2a',
  }),
  {
    foreground: '#e8e8e8',
    background: '#0a0a0a',
    comment: '#6a7a8a',
    keyword: '#ff3b5c',
    string: '#7fdbca',
    number: '#f0a060',
    constant: '#ff6b8a',
    function: '#e8f4ff',
    type: '#ff3b5c',
    variable: '#e8e8e8',
    parameter: '#c8d0d8',
    operator: '#ff3b5c',
    tag: '#ff3b5c',
    attribute: '#7fdbca',
    invalid: '#ff3b5c',
    invalidBackground: '#3a1018',
  },
)

export const DEADEYE_MIDNIGHT_THEME: ThemeDefinition = defineTheme(
  'deadeye-midnight',
  'Deadeye Midnight',
  'Deep black workstation tones with blue and purple accents.',
  'dark',
  'vs-dark',
  shell('#818cf8', {
    bgBase: '#030712',
    bgSurface: '#050816',
    bgElevated: '#0b1020',
    bgPanel: '#0f172a',
    bgHover: '#131c33',
    bgActive: '#182444',
    bgInput: '#0a1020',
    textPrimary: '#e2e8f0',
    textSecondary: '#cbd5e1',
    textMuted: '#94a3b8',
    textDisabled: '#64748b',
    borderSubtle: '#111827',
    borderDefault: '#1e293b',
    borderStrong: '#334155',
  }, { success: '#38bdf8' }),
  {
    foreground: '#e2e8f0',
    background: '#050816',
    comment: '#64748b',
    keyword: '#a78bfa',
    string: '#38bdf8',
    number: '#fbbf24',
    constant: '#c084fc',
    function: '#7dd3fc',
    type: '#a78bfa',
    variable: '#e2e8f0',
    parameter: '#cbd5e1',
    operator: '#818cf8',
    tag: '#a78bfa',
    attribute: '#38bdf8',
    invalid: '#f87171',
    invalidBackground: '#3f1212',
  },
)

export const DEADEYE_CARBON_THEME: ThemeDefinition = defineTheme(
  'deadeye-carbon',
  'Deadeye Carbon',
  'Graphite and metal surfaces with restrained professional contrast.',
  'dark',
  'vs-dark',
  shell('#9ca3af', {
    bgBase: '#0c0c0d',
    bgSurface: '#111113',
    bgElevated: '#161618',
    bgPanel: '#1a1a1d',
    bgHover: '#202024',
    bgActive: '#26262b',
    bgInput: '#141416',
    textPrimary: '#ececec',
    textSecondary: '#c4c4c4',
    textMuted: '#8b8b8f',
    textDisabled: '#5c5c60',
    borderSubtle: '#1f1f22',
    borderDefault: '#2a2a2e',
    borderStrong: '#3a3a40',
  }, { danger: '#ef4444', success: '#6b7280' }),
  {
    foreground: '#ececec',
    background: '#111113',
    comment: '#6b7280',
    keyword: '#d1d5db',
    string: '#a3a3a3',
    number: '#d4d4d8',
    constant: '#f4f4f5',
    function: '#e5e7eb',
    type: '#d4d4d8',
    variable: '#ececec',
    parameter: '#c4c4c4',
    operator: '#9ca3af',
    tag: '#d1d5db',
    attribute: '#a3a3a3',
    invalid: '#ef4444',
    invalidBackground: '#3f1515',
  },
)

export const DEADEYE_LIGHT_THEME: ThemeDefinition = defineTheme(
  'deadeye-light',
  'Deadeye Light',
  'Clean light professional theme for bright environments.',
  'light',
  'vs',
  shell('#0066cc', {
    bgBase: '#f3f4f6',
    bgSurface: '#ffffff',
    bgElevated: '#f9fafb',
    bgPanel: '#ffffff',
    bgHover: '#f3f4f6',
    bgActive: '#e5e7eb',
    bgInput: '#ffffff',
    textPrimary: '#111827',
    textSecondary: '#374151',
    textMuted: '#6b7280',
    textDisabled: '#9ca3af',
    borderSubtle: '#e5e7eb',
    borderDefault: '#d1d5db',
    borderStrong: '#cbd5e1',
  }, { danger: '#dc2626', warning: '#d97706', success: '#059669' }),
  {
    foreground: '#111827',
    background: '#ffffff',
    comment: '#6b7280',
    keyword: '#0066cc',
    string: '#047857',
    number: '#b45309',
    constant: '#be123c',
    function: '#1d4ed8',
    type: '#0066cc',
    variable: '#111827',
    parameter: '#374151',
    operator: '#0066cc',
    tag: '#0066cc',
    attribute: '#047857',
    invalid: '#dc2626',
    invalidBackground: '#fee2e2',
  },
)

export const DRACULA_THEME: ThemeDefinition = defineTheme(
  'dracula',
  'Dracula',
  'Classic Dracula palette with purple and pink highlights.',
  'dark',
  'vs-dark',
  shell('#bd93f9', {
    bgBase: '#21222c',
    bgSurface: '#282a36',
    bgElevated: '#2d2f3b',
    bgPanel: '#343746',
    bgHover: '#3a3d4b',
    bgActive: '#44475a',
    bgInput: '#282a36',
    textPrimary: '#f8f8f2',
    textSecondary: '#e2e2dc',
    textMuted: '#a0a0a8',
    textDisabled: '#6272a4',
    borderSubtle: '#383a4a',
    borderDefault: '#44475a',
    borderStrong: '#6272a4',
  }, { danger: '#ff5555', warning: '#ffb86c', success: '#50fa7b' }),
  {
    foreground: '#f8f8f2',
    background: '#282a36',
    comment: '#6272a4',
    keyword: '#ff79c6',
    string: '#f1fa8c',
    number: '#bd93f9',
    constant: '#bd93f9',
    function: '#50fa7b',
    type: '#8be9fd',
    variable: '#f8f8f2',
    parameter: '#ffb86c',
    operator: '#ff79c6',
    tag: '#ff79c6',
    attribute: '#50fa7b',
    invalid: '#ff5555',
    invalidBackground: '#4a1f28',
  },
)

export const NORD_THEME: ThemeDefinition = defineTheme(
  'nord',
  'Nord',
  'Arctic, bluish Nord color scheme.',
  'dark',
  'vs-dark',
  shell('#88c0d0', {
    bgBase: '#2e3440',
    bgSurface: '#2e3440',
    bgElevated: '#3b4252',
    bgPanel: '#3b4252',
    bgHover: '#434c5e',
    bgActive: '#4c566a',
    bgInput: '#2e3440',
    textPrimary: '#eceff4',
    textSecondary: '#d8dee9',
    textMuted: '#a3b1c2',
    textDisabled: '#616e88',
    borderSubtle: '#3b4252',
    borderDefault: '#434c5e',
    borderStrong: '#4c566a',
  }, { danger: '#bf616a', warning: '#ebcb8b', success: '#a3be8c' }),
  {
    foreground: '#eceff4',
    background: '#2e3440',
    comment: '#616e88',
    keyword: '#81a1c1',
    string: '#a3be8c',
    number: '#b48ead',
    constant: '#b48ead',
    function: '#88c0d0',
    type: '#8fbcbb',
    variable: '#eceff4',
    parameter: '#d8dee9',
    operator: '#81a1c1',
    tag: '#81a1c1',
    attribute: '#8fbcbb',
    invalid: '#bf616a',
    invalidBackground: '#4c2f35',
  },
)

export const MONOKAI_THEME: ThemeDefinition = defineTheme(
  'monokai',
  'Monokai',
  'Classic Monokai high-contrast coding colors.',
  'dark',
  'vs-dark',
  shell('#fd971f', {
    bgBase: '#1e1f1c',
    bgSurface: '#272822',
    bgElevated: '#2d2e28',
    bgPanel: '#2f302a',
    bgHover: '#383830',
    bgActive: '#3e3d32',
    bgInput: '#272822',
    textPrimary: '#f8f8f2',
    textSecondary: '#e6db74',
    textMuted: '#a59f85',
    textDisabled: '#75715e',
    borderSubtle: '#3e3d32',
    borderDefault: '#49483e',
    borderStrong: '#75715e',
  }, { danger: '#f92672', warning: '#fd971f', success: '#a6e22e' }),
  {
    foreground: '#f8f8f2',
    background: '#272822',
    comment: '#75715e',
    keyword: '#f92672',
    string: '#e6db74',
    number: '#ae81ff',
    constant: '#ae81ff',
    function: '#a6e22e',
    type: '#66d9ef',
    variable: '#f8f8f2',
    parameter: '#fd971f',
    operator: '#f92672',
    tag: '#f92672',
    attribute: '#a6e22e',
    invalid: '#f92672',
    invalidBackground: '#4a1f2d',
  },
)

export const BUILTIN_THEMES: readonly ThemeDefinition[] = [
  DEADEYE_DARK_THEME,
  DEADEYE_MIDNIGHT_THEME,
  DEADEYE_CARBON_THEME,
  DEADEYE_LIGHT_THEME,
  DRACULA_THEME,
  NORD_THEME,
  MONOKAI_THEME,
]
